GET http://localhost:3000/todos/?status=HR

###
GET http://localhost:3000/todos/3/

###
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 12,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}

###
PUT http://localhost:3000/todos/3/
Content-Type: application/json

{
  "dueDate": "2021-1-32"
}

###
GET http://localhost:3000/agenda/?date=2021-1-12